name: flutter_application_campus_view
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.4.3
  turn_page_transition: ^0.4.0
  flutter_layout_grid: ^2.0.7
  google_fonts: ^6.1.0
  media_kit: ^1.1.10 # 기본 메인 패키지
  media_kit_video: ^1.1.10 # 비디오 위젯
  media_kit_libs_windows_video: ^1.0.9 # Windows용 네이티브 라이브러리
  path: ^1.8.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/all_videos.json

    # 배경 이미지
    - assets/backgrounds/main_background.png
    - assets/backgrounds/campus_list_page.png
    - assets/backgrounds/college_menu_aiFusion.png
    - assets/backgrounds/college_menu_business.png
    - assets/backgrounds/college_menu_engineering.png
    - assets/backgrounds/college_menu_lifeAndHealthSciences.png
    - assets/backgrounds/college_menu_artsAndPhysicalEducation.png
    - assets/backgrounds/college_menu_humanitiesAndSocialSciences.png
    - assets/backgrounds/college_menu_liberalStudies.png

    # 버튼 아이콘
    - assets/button_icons/Home_hover.png
    - assets/button_icons/Home_idle.png

    - assets/button_icons/campus_main.png
    - assets/button_icons/campus1.jpg
    - assets/button_icons/campus2.jpg
    - assets/button_icons/campus3.jpg
    - assets/button_icons/campus4.jpg
    - assets/button_icons/campus5.jpg
    - assets/button_icons/campus6.jpg
    - assets/button_icons/campus7.jpg
    - assets/button_icons/button_next.png
    - assets/button_icons/button_prev.png
    - assets/button_icons/button_next_hover.png
    - assets/button_icons/button_prev_hover.png

    # AI융합대학 학과 아이콘
    - assets/button_icons/aiFusion/gameSoftware.jpg
    - assets/button_icons/aiFusion/semiconductorEngineering.jpg
    - assets/button_icons/aiFusion/bigDataAI.jpg
    - assets/button_icons/aiFusion/electronicEngineering.jpg
    - assets/button_icons/aiFusion/intelligentRobotics.jpg
    - assets/button_icons/aiFusion/computerEngineering.jpg

    # 경영대학 학과 아이콘
    - assets/button_icons/business/businessAdministration.jpg # 경영학부
    - assets/button_icons/business/globalCommerce.jpg # 글로벌통상학과
    - assets/button_icons/business/digitalFinanceManagement.jpg # 디지털금융경영

    # 공과대학 학과 아이콘
    - assets/button_icons/engineering/architecturalCivilEngineering.jpg
    - assets/button_icons/engineering/futureMobilityEngineering.jpg
    - assets/button_icons/engineering/safetyEngineering.jpg
    - assets/button_icons/engineering/informationCommunicationEngineering.jpg
    - assets/button_icons/engineering/architecture.jpg
    - assets/button_icons/engineering/fireDisasterPrevention.jpg
    - assets/button_icons/engineering/electricalEngineering.jpg
    - assets/button_icons/engineering/chemicalEngineering.jpg
    - assets/button_icons/engineering/mechanicalEngineering.jpg
    - assets/button_icons/engineering/systemControlEngineering.jpg
    - assets/button_icons/engineering/electronicMaterialsEngineering.jpg
    - assets/button_icons/engineering/environmentalEngineering.jpg

    # 생명보건대학 학과 아이콘
    - assets/button_icons/lifeAndHealthSciences/nursing.jpg
    - assets/button_icons/lifeAndHealthSciences/biotechnology.jpg
    - assets/button_icons/lifeAndHealthSciences/clinicalLaboratoryScience.jpg
    - assets/button_icons/lifeAndHealthSciences/animalHealthWelfare.jpg
    - assets/button_icons/lifeAndHealthSciences/foodEngineering.jpg
    - assets/button_icons/lifeAndHealthSciences/pharmaceuticalEngineering.jpg
    - assets/button_icons/lifeAndHealthSciences/physicalTherapy.jpg
    - assets/button_icons/lifeAndHealthSciences/foodNutrition.jpg
    - assets/button_icons/lifeAndHealthSciences/cosmeticScience.jpg

    # 예체능대학 학과 아이콘
    - assets/button_icons/artsAndPhysicalEducation/golfIndustry.jpg
    - assets/button_icons/artsAndPhysicalEducation/cultureAndMedia.jpg
    - assets/button_icons/artsAndPhysicalEducation/practicalMusic.jpg
    - assets/button_icons/artsAndPhysicalEducation/theaterTrack.jpg
    - assets/button_icons/artsAndPhysicalEducation/designSchool.jpg
    - assets/button_icons/artsAndPhysicalEducation/sportsForAll.jpg
    - assets/button_icons/artsAndPhysicalEducation/animation.jpg

    # 인문사회대학 학과 아이콘
    - assets/button_icons/humanitiesAndSocialSciences/christianStudies.jpg
    - assets/button_icons/humanitiesAndSocialSciences/socialWelfare.jpg
    - assets/button_icons/humanitiesAndSocialSciences/earlyChildhoodEducation.jpg
    - assets/button_icons/humanitiesAndSocialSciences/koreanLanguageCulture.jpg
    - assets/button_icons/humanitiesAndSocialSciences/mediaCommunication.jpg
    - assets/button_icons/humanitiesAndSocialSciences/industrialPsychology.jpg
    - assets/button_icons/humanitiesAndSocialSciences/chineseStudies.jpg
    - assets/button_icons/humanitiesAndSocialSciences/aviationService.jpg
    - assets/button_icons/humanitiesAndSocialSciences/lawPoliceAdministration.jpg
    - assets/button_icons/humanitiesAndSocialSciences/englishLanguageLiterature.jpg
    - assets/button_icons/humanitiesAndSocialSciences/youthCultureCounseling.jpg

    # 자유전공학부 학과 아이콘
    - assets/button_icons/liberalStudies/liberalArtsUndeclared.jpg

    # 썸네일
    - assets/thumbnails/aiFusion/gameSoftware/
    - assets/thumbnails/aiFusion/semiconductorEngineering/
    - assets/thumbnails/aiFusion/bigDataAI/
    - assets/thumbnails/aiFusion/electronicEngineering/
    - assets/thumbnails/aiFusion/intelligentRobotics/
    - assets/thumbnails/aiFusion/computerEngineering/

    - assets/thumbnails/business/businessAdministration/
    - assets/thumbnails/business/globalCommerce/
    - assets/thumbnails/business/digitalFinanceManagement/

    - assets/thumbnails/engineering/architecturalCivilEngineering/
    - assets/thumbnails/engineering/architecture/
    - assets/thumbnails/engineering/mechanicalEngineering/
    - assets/thumbnails/engineering/futureMobilityEngineering/
    - assets/thumbnails/engineering/fireDisasterPrevention/
    - assets/thumbnails/engineering/systemControlEngineering/
    - assets/thumbnails/engineering/safetyEngineering/
    - assets/thumbnails/engineering/electricalEngineering/
    - assets/thumbnails/engineering/electronicMaterialsEngineering/
    - assets/thumbnails/engineering/informationCommunicationEngineering/
    - assets/thumbnails/engineering/chemicalEngineering/
    - assets/thumbnails/engineering/environmentalEngineering/

    - assets/thumbnails/lifeAndHealthSciences/nursing/
    - assets/thumbnails/lifeAndHealthSciences/animalHealthWelfare/
    - assets/thumbnails/lifeAndHealthSciences/physicalTherapy/
    - assets/thumbnails/lifeAndHealthSciences/biotechnology/
    - assets/thumbnails/lifeAndHealthSciences/foodEngineering/
    - assets/thumbnails/lifeAndHealthSciences/foodNutrition/
    - assets/thumbnails/lifeAndHealthSciences/clinicalLaboratoryScience/
    - assets/thumbnails/lifeAndHealthSciences/pharmaceuticalEngineering/
    - assets/thumbnails/lifeAndHealthSciences/cosmeticScience/

    - assets/thumbnails/artsAndPhysicalEducation/golfIndustry/
    - assets/thumbnails/artsAndPhysicalEducation/cultureAndMedia/
    - assets/thumbnails/artsAndPhysicalEducation/practicalMusic/
    - assets/thumbnails/artsAndPhysicalEducation/theaterTrack/
    - assets/thumbnails/artsAndPhysicalEducation/designSchool/
    - assets/thumbnails/artsAndPhysicalEducation/sportsForAll/
    - assets/thumbnails/artsAndPhysicalEducation/animation/

    - assets/thumbnails/humanitiesAndSocialSciences/christianStudies/
    - assets/thumbnails/humanitiesAndSocialSciences/socialWelfare/
    - assets/thumbnails/humanitiesAndSocialSciences/earlyChildhoodEducation/
    - assets/thumbnails/humanitiesAndSocialSciences/koreanLanguageCulture/
    - assets/thumbnails/humanitiesAndSocialSciences/mediaCommunication/
    - assets/thumbnails/humanitiesAndSocialSciences/industrialPsychology/
    - assets/thumbnails/humanitiesAndSocialSciences/chineseStudies/
    - assets/thumbnails/humanitiesAndSocialSciences/aviationService/
    - assets/thumbnails/humanitiesAndSocialSciences/lawPoliceAdministration/
    - assets/thumbnails/humanitiesAndSocialSciences/englishLanguageLiterature/
    - assets/thumbnails/humanitiesAndSocialSciences/youthCultureCounseling/

    - assets/thumbnails/liberalStudies/liberalArtsUndeclared/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  # fonts:
  #   - family: ROKAF Sans
  #     fonts:
  #       - asset: fonts/ROKAF Sans Medium.otf
  #         weight: 500
  #       - asset: fonts/ROKAF Sans Bold.otf
  #         weight: 700
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
